default_language_version:
  python: python3.14

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    exclude: ^tests/fixtures/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.7
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: uv run mypy
    language: system
    pass_filenames: false
    always_run: true
