repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        always_run: true
