name: Changelog CI

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.2.0
